From python:3.10-buster
RUN mkdir streamlit-app && \
    apt-get update && apt-get install -y libx11-dev libeigen3-dev libccd-dev octomap-tools ffmpeg libsm6 libxext6
WORKDIR streamlit-app
COPY requirements_PDU4.txt .
COPY setup.sh .
RUN pip install --upgrade pip
RUN pip3 install -r requirements_PDU4.txt
ENV PORT=8086
RUN chmod +x setup.sh && ./setup.sh
CMD ["streamlit","run","Streamlit_App_v2/Main.py"]
EXPOSE 8086